---
application:
  name: "truekeapp"
  project: "Webapp"
  organization: "QoveryCommunity"
  publicy_accesible: true
  domain: my.truekee
routers:
- name: "main-truekeapp"
  routes:
  - application_name: "truekeapp"
    paths:
    - "/*"
