---
application:
  name: "truekeapp"
  project: "Webapp"
  organization: "QoveryCommunity"
  publicy_accesible: true
routers:
- name: "truekeapp"
  routes:
  - application_name: "truekeapp"
    paths:
    - "/*"
